### ISSUE TITLE
Webapp not working on Chrome

### ISSUE THREAD

**Issue by vigji** [DownesLab/Marigold#1]
Hi people, thanks for the very promising tool!

I would like to try out the web app. I am working on Chrome (Version 125.0.6422.176), on macOS (v17.5). 

I can make a new project, but the moment I go to `Start new dataset` > `Extract and label images` > `Load movie`, I select a movie (68 Mb in size), then nothing happens. I am stuck at the following screen:
<img width="1728" alt="Screenshot 2024-06-17 at 21 52 55" src="https://github.com/downeslab/marigold/assets/10400212/af3d43ae-07dd-4967-8924-e7266c570149">

I can't see the movie, although its size got correctly read (from the arena size values I read on the left).

Also, it fails if I try to load an `avi` file (nothing happens, not even name of the movie loaded appearing), so I assume `.avi` are not supported?

**Comment by vigji** [comment]
I've tested it on a Windows 10, using both Chrome and Edge - both recommended browsers - and I cannot fix the issue. I'd appreciate any feedback you could give on the matter!

**Comment by downeslab** [comment]
Thanks so much for your interest in using Marigold! I'm sorry you haven't been able to get it to work yet.

I suspect the issue is that your movie files are in a format we don't currently support. For now, Marigold is only compatible with movie files encoded using H.264/AVC compression in an MP4 container. I've added some documentation of that issue to the README and some example movie files that are known to work well. Can you first try using those to rule out any other issues with the web app? If that goes well, hopefully that means things should just work if you can convert your movie files to the recommended format. If not, we'll take it from there.

Feel free to reach out to me by email (gteicher at umass dot edu) if you need help converting the files to the recommended format. I don't want to endorse any specific tools here, but am happy to provide suggestions by email.

**Comment by vigji** [comment]
Great, thanks for the pointers! I'll try to recode them using `fffmpeg` (no shame in advertising if OS :) )! for reference of future users, here's the line I've run:

```
ffmpeg -i input_movie.ext -c:v libx264 -c:a aac -strict experimental -b:a 192k output_movie.mp4
```
